### ISSUE TITLE
No OS X build option?

### ISSUE THREAD

**Issue by rpw98** [wang-bin/build_ffmpeg#2]
Trying to build QtAV with FFmpeg with libx264 enabled. But I can't seem to find option for OS X? Why? And how do I enable specific codecs?

Thank you!

**Comment by wang-bin** [comment]
Add `MISC_OPT=--enable-libx264` in `config-.sh` and run `./build_ffmpeg.sh` or in `config-osx.sh` and run `./build_ffmpeg.sh osx`
