### ISSUE TITLE
Sets NDK_ROOT automatically

### ISSUE THREAD

**Issue by tdauth** [wang-bin/build_ffmpeg#3]
Although I have specified NDK_ROOT before your script "config-android.sh" overwrites my value. I had to remove the statement to use my own NDK_ROOT path.

**Comment by wang-bin** [comment]
you can set in config-android.sh

**Comment by tdauth** [comment]
Can I enabled static linking for Android in this file as well? I would like to link ffmpeg and QtAV statically. Maybe some information in the Wiki would help. I guess you can close this ticket.
